services:
  app:
    build: .
    ports:
      - "8080:1323"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/database?sslmode=disable
      JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ3ZHRTM4dENlSjJlNlMKU25jZkVaY1RyZlZIODdXNWdqOWNZdU1ERmwyWitTU1ZFengzUmxRdjVHdkdwY2xjelJnKzVQMHlpN3dpdEZBNgpEL0p6L1MyY2VNUlV2bkZ4NUQza28yVW0za2JUNzNFRHJMM0R2OUpyV2hXa0Q0cjdzK1l4RnU5MVdDNnFOZXNGCm96VnpVQW1yQ2tpYW94OFBISlQxMlBIZnVIWUw0TG9hY0c0dlo4TlFyUGtIWVpsdDJITUhGL2VOYjh1ZEhFSDQKbEVndlJmOWZrWnc0MkN0dk16MnlneDFKV2ZicWxnNUZ6OEhLb2x4ZnhWMnBaUmlJRUVGUEN4L1dqTThOMUpHbQp4Mkl2UHpWajFGZGE3M0tyS0xKV1IwOURMWVI0YWsvT0lpcHNhTlhoQjZsRDdqR29jYjJIb2l3bkZObDkvVEdpCkVJZ295THNmQWdNQkFBRUNnZ0VBQzRRU0Nsbks4KzBWSE0xYS9QeDAyWmdxWVZ0dEMxQytzV2tya2NDL0oraisKb3A0TG1iTlN4dEpEZmJndnF6UFlzV0pHMDRrNTRYVWNoYS9BMFh6SVZZU05NblJTdjhhSmhPZkk0bFUzaHFtTAozdmhWMlhHeCtZVGVRWUVTM0svSXB3S01LSnFaSkhGbXVMaUlROEpJTUlDbnBTRmFESmk0K2dacVpMMXhhTXg0CnpOUG1lOWhjRUphcUZnUmF2VHZTMVJOaFF3OTdob0JsSGZhRkhmSUdPeXFzZk1OeW5WdkNSSkJNSG92YU9VcnUKNkNQaHViN0M2MTJoQUZEblJOOWV1d3pRT2dZMGt0VW02OVZiWDMrZitldjVJaE1RcGFWY1JwcWpBWW43K21idApUWktwSG54Slh5OVBNL0o4QVBYSnRVUzlwcW1adFNsdkZqcmRaYUpFZ1FLQmdRRFVQMVpWSFhBQXFHWFJQS0E1ClhHUFl1R2d3aEJiVkR5Qko1eGNSdVRCK0lXdndmNnFqQWFFM3BhYXhGc3JlOWRESUJqUVZWKzB6VDdwTlZJWGsKUVFsMTViczM3bUp5R3ZsYS9idjJmeWlGMktXZkpobm9YN25CejBqbHB2V3c1WWh0aXBoaTYrbzk0SEhIelovZApzbHd3SVlpaGJHU0JEM0loU0hwbDdZYTAzd0tCZ1FEVE1GNEdLTFJiQ25naU9tTHZ1UUhHSlE5VzFwODZsRkw3ClBBUUNKaE1LSEV5YzdiUkZjZmFKa0o1Z2JXWUNBeE1sUGVzSGp0bTAzVUFLSTJKVHY3RjR1M3FEWXFwMHpXQlkKZzhUNEk1dENxa21GbndrTXZLeUlyQjU4MThUcFdRVXVLRGhQd2pld0lJbWZkbE1WRHZFNVd3YXpGNHNmeVNyUQpZbitIQjZxQndRS0JnRy9yVGh6bnZ1MjUzcWFzcjFoUDdaNlQ3dXpXV2l2VEpCV1VNOGYydlNsbGVrT0JMbnR5CkdvNzdYS0M1QWhUN3pqSUxnMTlWMUJCZ2xENit1VE9aVCtISldDV3dJRjFHK0FJUkZoSnZEdkUxUW5CZmFQM3QKckVnVWc3NEZnanpiYkV0RzhBQUpvcVVxT3hVK3luUGUzMW5KOVFBWjVnMWdGYkNUUldlR0RxaEZBb0dBTmoxMQo2SjhMczFZOUJJMTZXNWRvblR0bmRTWXFQeUZaTHExN1doSHRVZXR5d2R0TE1ZclRod0ZkcStadERKYzlrNU1UCmloMW1UTTJHWlJReGJORVBBN01qQkJ1VEsreVRraWhGcm5WMnF1aVJlWUFmRXVaaWFiZkxITVZPRGFDUGRBdGcKYXh1MnNjV3Brd3NReTVmSzNMQkVTRHNEd0dZcVdOcnpaZnJTRUFFQ2dZRUFxVEdKb1JaU2M2TlNaQm1SUi9zUwozYWhmYlIwYmhkSGdRSldjb3hBblJlaDdweDZMRVF5R0RiekFYZUh1K2UrdG94V21tSHdUbTZOSy9Da2V1L2sxCnZML2IzbGJ0eEVlaW9qSmVHMmZKZTJ5NlQ5SFkvL3J4VE0rNzZGMkZwKzcwZ29yZDBhWTBaVEI0clVKMmtPNWMKN3o1ZDlRbStFNGpEUXZFZHVqS0RmMmM9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
      JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyeGhOL0xRbmlkbnVra3AzSHhHWApFNjMxUi9PMXVZSS9YR0xqQXhaZG1ma2tsUk04ZDBaVUwrUnJ4cVhKWE0wWVB1VDlNb3U4SXJSUU9nL3ljLzB0Cm5IakVWTDV4Y2VROTVLTmxKdDVHMCs5eEE2eTl3Ny9TYTFvVnBBK0srN1BtTVJidmRWZ3VxalhyQmFNMWMxQUoKcXdwSW1xTWZEeHlVOWRqeDM3aDJDK0M2R25CdUwyZkRVS3o1QjJHWmJkaHpCeGYzalcvTG5SeEIrSlJJTDBYLwpYNUdjT05ncmJ6TTlzb01kU1ZuMjZwWU9SYy9CeXFKY1g4VmRxV1VZaUJCQlR3c2Yxb3pQRGRTUnBzZGlMejgxClk5UlhXdTl5cXlpeVZrZFBReTJFZUdwUHppSXFiR2pWNFFlcFErNHhxSEc5aDZJc0p4VFpmZjB4b2hDSUtNaTcKSHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      # Load database schema from ./database.sql
      # If you want to reload new database schema, you need to execute
      # `docker-compose down --volumes` first to remove the volume.
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db:
    driver: local
